name: Lint

on:
  push:
    paths:
      - 'src/**'    

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16.x', '20.x' ]

    # permissions:
      # contents: read
      # packages: read
        # To report GitHub Actions status checks
        #statuses: write

    steps:
      # To be deleted: Default super linter guide
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     # super-linter needs the full git history to get the
      #     # list of files that changed across commits
      #     fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      # - run: npm ci --speed up actions
      # - run: npm run build --if-present --speed up actions
      # - run: npm test -- --watch=false --browsers=ChromeHeadless
      - name: Super-linter
        uses: super-linter/super-linter@v6.2.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
