##Testing typescript

name: CI para Pull Request

on: 
  pull_request:
  paths:
  - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

  - name: Setup Angular Typescript
    uses: actions/setup-node@v3
    with:
      node-version: 16.x
  